stages:
- name: stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: myapp
- name: compile
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: java -version
timeout: 60
notification: {}
